# Generated by Django 2.2.25 on 2021-12-21 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.TextField()),
                ('soy_isim', models.TextField()),
                ('ogrenci_no', models.TextField()),
                ('ogrenim_tur', models.TextField()),
                ('ders_adi', models.TextField()),
                ('proje_ozeti', models.TextField()),
                ('proje_teslim_tarih', models.TextField()),
                ('donem', models.TextField()),
                ('proje_baslıgı', models.TextField()),
                ('anahtar_kelimeler', models.TextField()),
                ('danisman_bilgileri', models.TextField()),
                ('juri_bilgileri', models.TextField()),
                ('pdf', models.FileField(blank=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yazar')),
            ],
        ),
    ]
